service: safety-net

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6

functions:
  safetyNet:
    handler: scrape.endpoint
    events:
      - http:
          path: /
          method: get
    environment:
      FB_APP_ID:  ${ssm:fbAppId}
      FB_APP_SECRET: ${ssm:fbAppSecret}
      PERSPECTIVE_API_KEY: ${ssm:perspectiveApiKey}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux